### PR TITLE
Added Text-slider and Color palatte #1

### PR DESCRIPTION
**Pull request by sidhartha2002**
Bro, I have made some new updates . I have added a text-slider over  the old ones.
Kindly review my changes by accepting my PR.

Here is a glimpse how the web page looks like  👇

meme_generator final pic

### CODE REVIEW

**Comment by arunsahoo-xt** [comment]
Merged! Great Work

**Comment by sidhartha2002** [comment]
Hello there, actually you have merged my pull request but forgotten to add the **hackodex2023** label.

It was specified by the Organisers of Hackodex that labeled contributions (merged by the repository owner) will be added to the Dashboard. Since you have not done labeling , its not showing my progress in the Dashboard .

Kindly do the needful.

Here I have added a picture of my other repository contribution which will make you understand 👇

hackodex label

**Comment by arunsahoo-xt** [comment]
Done

**Comment by sidhartha2002** [comment]
Thanks a lot !

**Pull request merged**
