### PR TITLE
Add a text size editor and color picker to choose different colors for text inside meme image and the changes should reflect dynamically

### PR DESCRIPTION
**Pull request by gits-up**
In this modified code, the HTML code includes a color picker and a range slider for the text color and size, respectively. The onchange event handlers for these inputs call the changeTextColor() and changeTextSize() functions, which update the textColor and textSize variables and call the drawMeme() function to redraw the meme with the new text color and size.

The JavaScript code has been modified to include the textColor and textSize variables, which are initially set to white and 30, respectively. The changeTextColor() and changeTextSize() functions update these variables and call drawMeme() to redraw the meme.

The drawMeme() function has been modified to use the textColor and textSize variables to set the fill and stroke styles and font size for the text. The strokeText() and fillText() methods are called with the updated text and text position parameters.

With these modifications, users can now choose different colors and sizes for the text inside the meme image, and the changes will be reflected dynamically by editing the above codes.

### CODE REVIEW

**Comment by arunsahoo-xt** [comment]
Are you creating a new canvas to reflect these changes ?

**Comment by gits-up** [comment]
No, the above code is not creating a new canvas to reflect these changes. It is simply updating the existing canvas with the new text and color choices.

Do you want a new canvas?

**Comment by arunsahoo-xt** [comment]
No, actually i am not using any canvas...I am overlaying the text in top of the image element...and you need to change the color of  those two text.That was my idea but you already used the canvas.Please use Github pages to make the site live and if its working properly i will accept the pull.Inform me if you face any further issues.

**Comment by gits-up** [comment]
> No, actually i am not using any canvas...I am overlaying the text in top of the image element...and you need to change the color of those two text.That was my idea but you already used the canvas.Please use Github pages to make the site live and if its working properly i will accept the pull.Inform me if you face any further issues.

here you go https://gits-up.github.io/

**Comment by arunsahoo-xt** [comment]
Its not working...the canvas is not visible at first but it was taking height and width but after changing text size or color the height and width becomes zero.

**Pull request closed without merging**
