### PR TITLE
fix reponsive at meme section

### PR DESCRIPTION
**Pull request by mansir93**
I also optimize the css and fix some typos

### CODE REVIEW

**Comment by arunsahoo-xt** [comment]
Why only the meme section? Make the top portion responsive too

**Comment by mansir93** [comment]
All the other section is responsive already

**Comment by mansir93** [comment]
Check the pull request and I can add more features

**Comment by arunsahoo-xt** [comment]
> All the other section is responsive already

Its not....the top section is a row which is divided in three parts...one original image ,one text editor and another meme image....make them responsive for mobile screens such that those three are shows in a column one below each other

**Pull request merged**
